<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_received  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["AfterAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		if ($values['Amount_TL']==null)
	$values['Amount_TL']=0;
$sql = "INSERT INTO Sent (Transaction_date, From_Account, To_Account, Amount_$, Amount_TL) VALUES ('".$values['date']."', ".$values['Received_From'].", ".$values['To_Account'].", ".$values['Amount_$'].", ".$values['Amount_TL'].")";
DB::exec($sql);
$sql = "UPDATE Account 
        SET Balance_$ = ifnull(Balance_$,0) + ".$values['Amount_$']." 
        WHERE idAccount = ".$values['To_Account'];
DB::exec($sql);
$sql = "UPDATE Account 
        SET Balance_$ = ifnull(Balance_$,0) - ".$values['Amount_$']." 
        WHERE idAccount = ".$values['Received_From'];
DB::exec($sql);

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
