<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_sent  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;



		$this->events["ProcessValuesAdd"]=true;

		$this->events["BeforeShowAdd"]=true;

		$this->events["BeforeProcessAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		if ($values['Amount_TL']==null)
	$values['Amount_TL']=0;
$sql = "INSERT INTO Received (date, To_Account, Received_From, Description, Amount_$, Amount_TL) VALUES ('".$values['Transaction_date']."', ".$values['To_Account'].", ".$values['From_Account'].", null, ".$values['Amount_$'].", ".$values['Amount_TL'].")";
DB::exec($sql);
$sql = "UPDATE Account 
        SET Balance_$ = ifnull(Balance_$,0) - ".$values['Amount_$']." 
        WHERE idAccount = ".$values['From_Account'];
DB::exec($sql);
$sql = "UPDATE Account 
        SET Balance_$ = ifnull(Balance_$,0) + ".$values['Amount_$']." 
        WHERE idAccount = ".$values['To_Account'];
DB::exec($sql);

if ($values['Order_ID'] != null) {
    // Update Order Balance
    $sql = "UPDATE `Order` 
            SET `Order_Balance` = IFNULL(`Order_Balance`, 0) - " . $values['Amount_$'] . "
            WHERE `idOrder` = " .$values['Order_ID'];
    DB::exec($sql);
}
$pageObject->setProxyValue('saved', true);

$pageObject->stopPRG = true;

	//Update customer balance
//}

//echo $sql;
//echo DB::LastError();
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Process record values
function ProcessValuesAdd(&$values, $pageObject)
{

		$values['Order_ID']=$_SESSION['Order_ID'];

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function ProcessValuesAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, $pageObject)
{

		//$_SESSION["Order_ID"]=$_GET["order"];
//$pageObject->setProxyValue("order",$_SESSION["Order_ID"]);
$pageObject->hideField("Order_ID");
;		
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
				// Add page: Before process
function BeforeProcessAdd($pageObject)
{

		$_SESSION['Order_ID']=$_GET["order"];


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
